### ISSUE TITLE
Doesn't work with Unity 2020

### ISSUE THREAD

**Issue by hex** [su10/AutoScreen#1]
It seems that in Unity 2020 it this great plugin doesn't work anymore. 

In **GameViewProxy.cs**, this line returns `null`. I think that `hasFocus` is not present anymore.

```private static readonly PropertyInfo HasFocus = GameView.GetProperty("hasFocus", InstanceFlag);```

**Comment by su10** [comment]
Please try this version: https://github.com/su10/AutoScreen-for-Device-Simulator
